SW-5557 manage an assurance visit
ministryofjustice/opg-sirius-supervision-deputy-hub pull request #149
Opened 2022-06-28 13:57 UTC by hiboabd

2022-06-29 13:46 UTC, denialanderror requested changes
Why have the Cypress file extensions been renamed?

2022-06-29 13:46 UTC, denialanderror commented on json-server/routes.json
> +    "/reference-data/ragRating": "/ragRating"
This isn't how we should be doing routing. The routes file is just for custom routes. All of this reference data could be in the same object for instance.

2022-07-01 08:39 UTC, ramchale approved these changes

2022-07-01 09:44 UTC, denialanderror approved these changes

2022-07-01 11:48 UTC, merged