Sw 5013 add download client
ministryofjustice/opg-sirius-supervision-deputy-hub pull request #59
Opened 2022-02-03 16:00 UTC by Nicholassully

2022-02-04 10:20 UTC, denialanderror requested changes

2022-02-04 10:20 UTC, denialanderror commented on docker/sirius-deputy-hub/Dockerfile
> +#RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.4
This change isn't needed

2022-02-04 13:29 UTC, Nicholassully commented on docker/sirius-deputy-hub/Dockerfile
> +#RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.4
done

2022-02-07 16:25 UTC, denialanderror approved these changes
Approved, but run the formatter just to check

2022-02-07 16:25 UTC, denialanderror commented on internal/server/deputy_hub.go
> +	"github.com/ministryofjustice/opg-sirius-supervision-deputy-hub/internal/sirius"
Could you run the formatter over this? I'm guessing this change is because of a disagreement between the formatter and your IDE.

2022-02-08 09:34 UTC, denialanderror approved these changes

2022-02-08 10:24 UTC, merged